//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TileView : ObjectView {
	public override void SetVisible (bool value)
	{
		Tile tile = Map.Instance.GetTile (position.x, position.y);
		if(null == tile) {
			throw new System.Exception("out of map position");
		}
		display.text = ".";
		if(true == value) {
			display.color = new Color(display.color.r, display.color.g, display.color.b, 1.0f);
			if(0 < tile.objects.Count)
			{
				display.text = "";
			}
		}
		else {
			if(true == tile.visit)
			{
				display.color = new Color(display.color.r, display.color.g, display.color.b, 0.5f);
			}
			else{
				display.text = "";
			}
		}
	}
}

